### ISSUE TITLE
Add the license tag on itch.io

### ISSUE THREAD

**Issue by remram44** [stuarttempleton/project-starscan#2]
Adding the [`GNU General Public License v2.0 (GPL)`](https://itch.io/games/code-gpl2) tag on your itch.io page will help people looking for opensource games!

You can set it in [Edit > Metadata > Release info](https://itch.io/game/release-info/1068270)

**Comment by stuarttempleton** [comment]
Oh thanks so much for the tip on that tag! I added the license tag on Itch for "code". I really appreciate this tip!
